//
// Created by Boris Bozhilov on 5/30/2026.
//

#ifndef OBJECT_ORIENTED_PROGRAMMING_FMI_2026_VEHICLEFACTORY_H
#define OBJECT_ORIENTED_PROGRAMMING_FMI_2026_VEHICLEFACTORY_H



class VehicleFactory {

};



#endif //OBJECT_ORIENTED_PROGRAMMING_FMI_2026_VEHICLEFACTORY_H
