//
// Created by Boris Bozhilov on 4/18/2026.
//

#ifndef OBJECT_ORIENTED_PROGRAMMING_FMI_2026_REGISTRATION_H
#define OBJECT_ORIENTED_PROGRAMMING_FMI_2026_REGISTRATION_H



class Registration {

};



#endif //OBJECT_ORIENTED_PROGRAMMING_FMI_2026_REGISTRATION_H
