//
// Created by Boris Bozhilov on 4/6/2026.
//

#ifndef OBJECT_ORIENTED_PROGRAMMING_FMI_2026_IMAGE_H
#define OBJECT_ORIENTED_PROGRAMMING_FMI_2026_IMAGE_H


class Image {
};


#endif //OBJECT_ORIENTED_PROGRAMMING_FMI_2026_IMAGE_H