//
// Created by Boris Bozhilov on 4/13/2026.
//

#ifndef OBJECT_ORIENTED_PROGRAMMING_FMI_2026_EMPLOYEE_H
#define OBJECT_ORIENTED_PROGRAMMING_FMI_2026_EMPLOYEE_H



class Employee {

};



#endif //OBJECT_ORIENTED_PROGRAMMING_FMI_2026_EMPLOYEE_H
