//
// Created by Boris Bozhilov on 4/2/2026.
//

#ifndef OBJECT_ORIENTED_PROGRAMMING_FMI_2026_NVECTOR_H
#define OBJECT_ORIENTED_PROGRAMMING_FMI_2026_NVECTOR_H


class NVector {
};


#endif //OBJECT_ORIENTED_PROGRAMMING_FMI_2026_NVECTOR_H